"""creates the foreign key to the user table

Revision ID: 898c591f6665
Revises: ce5ec4406cd4
Create Date: 2019-12-17 00:23:15.563670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898c591f6665'
down_revision = 'ce5ec4406cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'user_id')
    # ### end Alembic commands ###
